grafana:
  enabled: false

alertmanager:
  enabled: false

prometheusOperator:
  admissionWebhooks:
    enabled: false
  tls:
    enabled: false

defaultRules:
  create: false

coreDns:
  enabled: false

kubeApiServer:
  enabled: false

kubeControllerManager:
  enabled: false

kubeEtcd:
  enabled: false

kubeProxy:
  enabled: false

kubeScheduler:
  enabled: false