{
 "title": "Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Node Health",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (node) (kube_node_status_condition{condition=\"Ready\",status=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deployment Ready/Unavailable Replicas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (node) (kube_deployment_status_replicas_available{namespace=\"kristian-lab\", deployment=\"kristian-web\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (node) (kube_deployment_status_replicas_unavailable{namespace=\"kristian-lab\", deployment=\"kristian-web\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Restart Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pod) (kube_pod_container_status_restarts_total{namespace=\"kristian-lab\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"kristian-lab\", image!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage in Pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"kristian-lab\", image!=\"\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}