server {
    listen 8080;
    server_name localhost;

    location = /healthz {
        root /usr/share/nginx/html;
    }

    location /internal/ {
        auth_basic "Restricted";
        auth_basic_user_file /etc/nginx/auth/.htpasswd;
        root /usr/share/nginx/html;
        index index.html;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
}