---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nginx-basic-auth
  namespace: kristian-lab
spec:
  encryptedData:
    .htpasswd: AgB+MpjqSRmj6AQXwD5eT9biMZwfQ1+3/NIz85Y3jpk2OZGZ46ZexxBUrAAGkV8f+2DFMuT707z87McLxOmJhaYmMP+kFV/bHHxX8uXkXIhuGGEJpRFHuV2E16j6qyz8DMBxXMUAtk/8+hjjFRMylYdNX2GvkCwisKidkCkx3Jcm2fr3zxNd/XcK1pP8lWhQWfb5Y8UkpTo+hOGLAmBa5zUGs/PwDwxGRwfmUXi2/96ULwMvaeaRbQxTPhzuqEAE5H9Qh4vJ9KZN5fYHOcVFZZKAeUfwQYd+YonIOa4BETcd0qNO+Pr/U6J9tRVGnpefPv7d7FO4r0H0fLIHTR4jd+k74QDSo2gOT1HPIC9e/X2DXriLToi8bf7n1s87nzo6OoFAqc8Akp/11DnYLI6RNqd/rbVLJ6RMQxt+ysW+f0cnShAJnvhbonUDN6Z8/6kSIrRDTeiO0oPZm5BXxCWEZuXVv44VF0lE1RR9r+KYvmQBSqaPn1aJfsax6sIBKqAbn+E3n7q6jZ9vLuizyumLK39VQ1GoeRrBl4z/cBZJ62rynIOhFxfAusd6Xg+rKlNJjgF/wFhZW4fEmJViOOFUCg+SL9+aTeTvr5sNs98dPZudUSPmFDplbIAT+SYzr9FC1T3k3meDGdP7j/T9HL9LqoY6g0kaWwjDL05xXvc4X1YJtyspCOtx16DjDVW83Z3T8LuYctD8opGGkoHD6cZ019nj+SkKCOABNLcfppIn8FN5NbJbZsqDII2EREdJeT1HglqzXy4CI/QgT4F2aI6vsQ+k0A==
  template:
    metadata:
      name: nginx-basic-auth
      namespace: kristian-lab
