---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nginx-basic-auth
  namespace: kristian-lab
spec:
  encryptedData:
    .htpasswd: AgDNoigcBZJVS8b1yFireXm6YXPyQz9dcubdpWqXS3IBgIuhmMOJUkmr5ePwTmBUIY3iufac44W00EdW1VA2f4KRMS5v89MuT5zySDfpF4c4o7rsaZrrgWagXLGu7mFRMqGUR+4ndHX8yLAdIPzuQN2u3SGGWQ5ZEMMP0Rwfs1UjfDgE28t/qMDuormP2lbJqD3fasVyU3C1t+RfKIbxI5xxiDxXxcTeWl85BstC+1FWVaGdzC3mRiEee5DEkYkc6+7ieFv5Pclm8UF/3Xa33TYJwbyuFjlks7ISpL2WYavb5gq0lmNZWyYaxLI13lq/RW7mVQ8Yl9jX/4c2nT43MvtGmyESpvu2le8jP+5HuDg+d8nk72kRzqyDoNfbWKpJISDi5Mqn2VfuLU2lg5K65BA5ZTaS84BwPun1611/DVi2XnZ+0CogbS9N5XnxyWViC5jhrU+Z27oKMJ9r7Ql9CadptPz94UB+bxjZBdyrRtBXZIQEn1xjFVBtjudrCxqAQAvZn2N4EVK17hfqXaBgycfhgqXgNxB6cqInCoQZ3Dxve8B2mH0UNZ0Yfx+po+aNyhng/9dmqFm8Aj+reMYEotJT6/BsNnA/ithjezheeY/izPuZI8ecgGA7jw0WYp5et9YpuPBLrep7LiX9xJGPqFJIMLkZ5VtLmTVoc+cvy0HcqsaAYJBkD2W7COqhThXULQxDabc2JbTyJeEU7V36VQOoeZy4HlAie7SoEVsrw9w1sGvJrR+Wid+2UEZKk/TBnCdkUMhUXp+BVB+iRcmcCSB97uf/
  template:
    metadata:
      name: nginx-basic-auth
      namespace: kristian-lab
